const SHEETS_ENDPOINT = "https://script.google.com/macros/s/AKfycbxMk_szuGn73oWQmXuuKIoKcsmt2tAcQcaqlM8iAUI1NkByKWdAtCmC42IuM-A_WfmY/exec";
const AI_BASE_URL = "http://111.228.46.150:3000/v1";
const AI_API_KEY = "sk-BtsZuSh7mCzjwPmke9ZzuCqnJPOucf6KXfHrdrVtglpNjYdm";
const AI_MODEL = "wj-interpret";
const QUESTION_COUNT = 19;

const variants = [
  {title:"Вариант 1",questions:[
    ["Сколько двоичных цифр составляет одну триаду?",["Восемь","Четыре","Три","Две"],2],["Какие цифры используются в восьмеричной системе счисления?",["От 0 до 9","От 0 до 8","От 0 до 7","От 1 до 8"],2],["Какая триада соответствует восьмеричной цифре 7?",["111","011","101","000"],0],["Какое основание у восьмеричной системы счисления?",["16","2","8","10"],2],["Чему равно 572₈ в двоичной системе?",["11010111","001010111","101111010","111010101"],0],["В какую сторону группируют двоичную запись при переводе в восьмеричную систему?",["Слева направо","От центра к краям","Произвольно","Справа налево"],3],["При переводе из двоичной системы в восьмеричную двоичную запись группируют слева направо.",["Верно","Неверно"],1],["Каждой восьмеричной цифре соответствует триада из трёх двоичных цифр.",["Верно","Неверно"],0],["В какую восьмеричную запись переводится число 202₁₀?",null,"312"],["Чему равно число 641₈ в десятичной системе счисления?",null,"417"]]},
  {title:"Вариант 2",questions:[
    ["Какое основание имеет восьмеричная система счисления?",["8","10","2","16"],0],["Чему равно число 202₁₀ в восьмеричной системе?",["312₈","128₈","167₈","238₈"],0],["Сколько двоичных цифр соответствует одной восьмеричной цифре?",["три","четыре","две","восемь"],0],["Какой диапазон цифр используется в восьмеричной системе?",["от 1 до 7","от 1 до 8","от 0 до 8","от 0 до 7"],3],["Как группируют двоичную запись при переводе в восьмеричную систему?",["Справа налево по две цифры","Слева направо по четыре цифры","Слева направо по три цифры","Справа налево по три цифры"],3],["Какое число получится при переводе 11010111₂ в восьмеричную систему?",["327","238","572","167"],2],["В восьмеричной системе счисления используются цифры от 0 до 8.",["Верно","Неверно"],1],["Каждой восьмеричной цифре соответствует четыре двоичные цифры.",["Верно","Неверно"],1],["Чему равно число 119₁₀ в восьмеричной системе?",null,"167"],["Чему равно число 356₈ в десятичной системе счисления?",null,"238"]]},
  {title:"Вариант 3",questions:[
    ["Какая восьмеричная цифра соответствует двоичной триаде 111?",["7","6","8","0"],0],["Почему связь восьмеричной системы с двоичной особенно удобна?",["8 = 2 + 6","8 = 2³","8 = 2²","8 = 2⁴"],1],["Какой двоичной триаде соответствует восьмеричная цифра 7?",["111","011","110","101"],0],["Как переводится двоичное число в восьмеричное?",["Умножением на 2³","Группировкой слева направо по две","Группировкой справа налево по три","Делением на 8"],2],["Сколько двоичных цифр заменяет одна восьмеричная цифра?",["две","четыре","три","одну"],2],["В каком порядке читаются остатки при переводе десятичного числа в восьмеричное?",["В прямом порядке","Слева направо","В обратном порядке","В порядке деления"],2],["Восьмеричная система связана с двоичной тем, что 8=2³.",["Верно","Неверно"],0],["При переводе двоичного числа в восьмеричное запись группируют справа налево по три цифры.",["Верно","Неверно"],0],["Переведите 356₈ в десятичную систему счисления.",null,"238"],["Запишите результат перевода 202₁₀ в восьмеричную систему.",null,"312"]]},
  {title:"Вариант 4",questions:[
    ["Почему запись 128₈ невозможна?",["Цифра 1 не входит в алфавит","Число слишком большое","Цифра 8 не входит в восьмеричный алфавит","Основание должно быть 10"],2],["Какие цифры входят в алфавит восьмеричной системы счисления?",["От 0 до 7","От 1 до 8","От 0 до 8","От 0 до 9"],0],["Сколько двоичных цифр составляет одна триада?",["8","3","4","2"],1],["По сколько цифр группируют двоичную запись при переводе в восьмеричную систему?",["По две","По три","По восемь","По четыре"],1],["Какая из записей невозможна в восьмеричной системе счисления?",["356₈","572₈","128₈","641₈"],2],["Чему равно 572₈ в двоичной системе?",["111010101","11010111","001010111","101111010"],1],["Каждой восьмеричной цифре соответствует четыре двоичные цифры.",["Верно","Неверно"],1],["При переводе десятичного числа в восьмеричное остатки читают в прямом порядке.",["Верно","Неверно"],1],["Переведите 119₁₀ в восьмеричную систему счисления.",null,"167"],["Запишите результат перевода 202₁₀ в восьмеричную систему.",null,"312"]]}
];

const commonQuestions = [
  ["Исправьте утверждение: восьмеричная система использует цифры от 0 до 9.",["От 0 до 7","От 1 до 8","От 0 до 8","От 0 до 9"],0],
  ["Для перехода из десятичной системы в восьмеричную число делят на...",["2","8","10","3"],1],
  ["Каждой цифре восьмеричной системы соответствует группа из... двоичных знаков.",["2","4","3","8"],2],
  ["Запись 58₈ корректна.",["Верно","Неверно"],1],
  ["При переходе из десятичной системы остатки от деления на 8 читают...",["в прямом порядке","в обратном порядке","слева направо без изменений","по два"],1],
  ["Почему между восьмеричной и двоичной системами не нужно выполнять деление?",null,"Потому что 8 = 2³ и каждой восьмеричной цифре соответствует триада"],
  ["Что заменяет одну цифру восьмеричной системы при переходе через двоичную?",["Триада из трёх двоичных знаков","Четыре двоичных знака","Две двоичные знака","Одна десятичная цифра"],0],
  ["Переведите число 73₁₀ в восьмеричную систему.",null,"111"],
  ["Переведите число 58₁₀ в восьмеричную систему.",null,"72"]
];

let selectedVariant = Math.floor(Math.random() * variants.length);
const $ = selector => document.querySelector(selector);
const questions = () => [...variants[selectedVariant].questions, ...commonQuestions];

function drawCardCanvas(canvas){const ctx=canvas.getContext('2d');canvas.width=canvas.clientWidth*devicePixelRatio;canvas.height=canvas.clientHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);ctx.strokeStyle='rgba(101,255,155,.18)';for(let x=20;x<canvas.clientWidth;x+=42){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.clientHeight);ctx.stroke()}for(let y=18;y<canvas.clientHeight;y+=30){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.clientWidth,y);ctx.stroke()}}
function renderQuiz(){const qs=questions();$('#quiz').innerHTML=qs.map((q,i)=>{const open=!q[1],numeric=i>=17;const options=open?'':`<div class="options">${q[1].map((o,j)=>`<div class="option"><input type="radio" name="q${i}" id="q${i}-${j}" value="${j}"><label for="q${i}-${j}">${String.fromCharCode(1040+j)}) ${o}</label></div>`).join('')}</div>`;return `<article class="question panel" id="question-${i}"><canvas class="question-canvas" aria-hidden="true"></canvas><div class="question-content"><div class="question-head"><span class="question-number">${String(i+1).padStart(2,'0')}</span><h3 class="question-title">${q[0]}</h3><span class="question-type">${open?'ОТКРЫТЫЙ ОТВЕТ':q[1].length===2?'ВЕРНО / НЕВЕРНО':'ОДИН ОТВЕТ'}</span></div>${open?`<div class="answer-input"><input type="${numeric?'number':'text'}" ${numeric?'inputmode="numeric" step="1" min="0"':''} name="q${i}" aria-label="Ответ на задание ${i+1}" placeholder="${numeric?'Введите число':'Введите ответ'}"></div>`:options}</div></article>`}).join('');document.querySelectorAll('.question-canvas').forEach(drawCardCanvas);document.querySelectorAll('#quiz input').forEach(x=>x.addEventListener('input',updateProgress));updateProgress()}
function getAnswers(){return Array.from({length:QUESTION_COUNT},(_,i)=>{const radio=document.querySelector(`[name=q${i}]:checked`),text=document.querySelector(`[name=q${i}][type=text], [name=q${i}][type=number]`);return radio?radio.value:(text?.value.trim()||'')})}
function updateProgress(){const a=getAnswers(),n=a.filter(Boolean).length,p=Math.round(n/QUESTION_COUNT*100);$('#progressText').textContent=`${n} из ${QUESTION_COUNT} отвечено`,$('#progressPercent').textContent=`${p}%`,$('#progressBar').style.width=`${p}%`}
function normalize(v){return String(v).toLowerCase().replace(/[₈₁₀₂]/g,'').replace(/\s+/g,'').replace(/[^0-9a-zа-я]/gi,'')}
function scoreQuiz(){const qs=questions(),answers=getAnswers();return qs.map((q,i)=>{const answer=answers[i],correct=q[1]?String(q[2]):q[2];return {number:i+1,answer,correct,open:!q[1],isCorrect:!!answer&&normalize(answer)===normalize(correct),question:q[0]}})}
async function checkOpenAnswer(row){if(!row.answer)return false;try{const response=await fetch(`${AI_BASE_URL}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${AI_API_KEY}`},body:JSON.stringify({model:AI_MODEL,temperature:0,messages:[{role:'system',content:'Проверь учебный ответ. Верни только JSON без markdown в формате {"correct":true} или {"correct":false}. Считай ответ правильным, если смысл совпадает с эталоном, даже при другой формулировке.'},{role:'user',content:`Вопрос: ${row.question}\nЭталон: ${row.correct}\nОтвет ученика: ${row.answer}`}]})});if(!response.ok)throw new Error(`AI HTTP ${response.status}`);const data=await response.json();const text=data.choices?.[0]?.message?.content||'';const parsed=JSON.parse(text.match(/\{[\s\S]*\}/)?.[0]||'{}');return parsed.correct===true}catch(error){console.warn('AI check failed, local answer check kept',error);return row.isCorrect}}
async function saveResult(results){const completedAt=new Date().toISOString();const payload={action:'save',studentName:$('#studentName').value.trim(),variant:selectedVariant+1,completedAt,score:results.filter(x=>x.isCorrect).length,total:QUESTION_COUNT,answers:results,results:JSON.stringify(results)};if(SHEETS_ENDPOINT)try{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),10000);await fetch(SHEETS_ENDPOINT,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify(payload),signal:controller.signal,keepalive:true});clearTimeout(timeout);payload.saved=true}catch(error){payload.saved=false;console.warn('Google Sheets save failed',error)}return payload}
function requestAiReview(payload){if(!SHEETS_ENDPOINT||!payload.answers.some(row=>row.open&&row.answer))return;fetch(SHEETS_ENDPOINT,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify({...payload,action:'ai-review'}),keepalive:true}).catch(error=>console.warn('AI review request failed',error))}
async function finish(){const name=$('#studentName').value.trim();if(!name){$('#studentName').focus();$('#studentName').setCustomValidity('Введите имя и фамилию');$('#studentName').reportValidity();return}$('#studentName').setCustomValidity('');const results=scoreQuiz();const payload=await saveResult(results);requestAiReview(payload);renderResults(results,payload.saved)}
function renderResults(rows,saved){$('#quizForm').hidden=true;const correct=rows.filter(x=>x.isCorrect).length;$('#results').hidden=false;$('#results').innerHTML=`<div class="section-kicker">СЕАНС ЗАВЕРШЁН // ВАРИАНТ ${selectedVariant+1}</div><h2>Результат для ${$('#studentName').value.trim()}</h2><div class="score">${correct} / ${QUESTION_COUNT}</div><p class="field-hint">${saved?'Результат сохранён. Открытые ответы дополнительно проверяются нейросетью в таблице.':'Не удалось подтвердить отправку в таблицу. Проверьте настройки Apps Script.'}</p><div class="result-list">${rows.map(r=>`<div class="result-row ${r.answer?(r.isCorrect?'correct':'wrong'):'unanswered'}"><span class="result-icon">${r.answer?(r.isCorrect?'OK':'×'):'—'}</span><span><strong>${String(r.number).padStart(2,'0')}</strong> ${r.question}</span><span class="result-answer">${r.answer?`Ваш ответ: ${r.answer}`:'Нет ответа'}${r.isCorrect?'':`<br>Ключ: ${r.correct}`}</span></div>`).join('')}</div>`;window.scrollTo({top:0,behavior:'smooth'})}

$('#finishButton').addEventListener('click',()=>{const firstMissing=getAnswers().findIndex(answer=>!answer);if(firstMissing>=0){$('#confirmText').textContent=`Не заполнено заданий: ${getAnswers().filter(answer=>!answer).length}. После подтверждения работа будет сохранена.`;$('#confirmModal').hidden=false;$('#cancelFinish').onclick=()=>{$('#confirmModal').hidden=true;document.querySelector(`#question-${firstMissing}`).scrollIntoView({behavior:'smooth',block:'center'})};}else finish()});$('#confirmFinish').addEventListener('click',()=>{$('#confirmModal').hidden=true;finish()});
const matrix=$('#matrix'),mctx=matrix.getContext('2d');let drops=[];function resizeMatrix(){matrix.width=innerWidth*devicePixelRatio;matrix.height=innerHeight*devicePixelRatio;mctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);drops=Array(Math.ceil(innerWidth/18)).fill(1)}function matrixFrame(){mctx.fillStyle='rgba(0,0,0,.16)';mctx.fillRect(0,0,innerWidth,innerHeight);mctx.fillStyle='#65ff9b';mctx.shadowColor='#65ff9b';mctx.shadowBlur=7;mctx.font='bold 15px monospace';drops.forEach((y,i)=>{mctx.fillText(String(Math.floor(Math.random()*8)),i*18,y*18);if(y*18>innerHeight&&Math.random()>.985)drops[i]=0;drops[i]+=.22});requestAnimationFrame(matrixFrame)}addEventListener('resize',resizeMatrix);resizeMatrix();matrixFrame();renderQuiz();
