const SHEETS_ENDPOINT = "https://script.google.com/macros/s/AKfycbxMk_szuGn73oWQmXuuKIoKcsmt2tAcQcaqlM8iAUI1NkByKWdAtCmC42IuM-A_WfmY/exec";
const AI_BASE_URL = "http://111.228.46.150:3000/v1";
const AI_API_KEY = "sk-BtsZuSh7mCzjwPmke9ZzuCqnJPOucf6KXfHrdrVtglpNjYdm";
const AI_MODEL = "wj-interpret";
const QUESTION_COUNT = 19;

const variants = [
  {title:"Вариант 1",questions:[
    ["Сколько двоичных цифр составляет одну триаду?",["Восемь","Четыре","Три","Две"],2],["Какие цифры используются в восьмеричной системе счисления?",["От 0 до 9","От 0 до 8","От 0 до 7","От 1 до 8"],2],["Какая триада соответствует восьмеричной цифре 7?",["111","011","101","000"],0],["Какое основание у восьмеричной системы счисления?",["16","2","8","10"],2],["Чему равно 572₈ в двоичной системе?",["11010111","001010111","101111010","111010101"],0],["В какую сторону группируют двоичную запись при переводе в восьмеричную систему?",["Слева направо","От центра к краям","Произвольно","Справа налево"],3],["При переводе из двоичной системы в восьмеричную двоичную запись группируют слева направо.",["Верно","Неверно"],1],["Каждой восьмеричной цифре соответствует триада из трёх двоичных цифр.",["Верно","Неверно"],0],["В какую восьмеричную запись переводится число 202₁₀?",null,"312"],["Чему равно число 641₈ в десятичной системе счисления?",null,"417"]]},
  {title:"Вариант 2",questions:[
    ["Какое основание имеет восьмеричная система счисления?",["8","10","2","16"],0],["Чему равно число 202₁₀ в восьмеричной системе?",["312₈","128₈","167₈","238₈"],0],["Сколько двоичных цифр соответствует одной восьмеричной цифре?",["три","четыре","две","восемь"],0],["Какой диапазон цифр используется в восьмеричной системе?",["от 1 до 7","от 1 до 8","от 0 до 8","от 0 до 7"],3],["Как группируют двоичную запись при переводе в восьмеричную систему?",["Справа налево по две цифры","Слева направо по четыре цифры","Слева направо по три цифры","Справа налево по три цифры"],3],["Какое число получится при переводе 11010111₂ в восьмеричную систему?",["327","238","572","167"],2],["В восьмеричной системе счисления используются цифры от 0 до 8.",["Верно","Неверно"],1],["Каждой восьмеричной цифре соответствует четыре двоичные цифры.",["Верно","Неверно"],1],["Чему равно число 119₁₀ в восьмеричной системе?",null,"167"],["Чему равно число 356₈ в десятичной системе счисления?",null,"238"]]},
  {title:"Вариант 3",questions:[
    ["Какая восьмеричная цифра соответствует двоичной триаде 111?",["7","6","8","0"],0],["Почему связь восьмеричной системы с двоичной особенно удобна?",["8 = 2 + 6","8 = 2³","8 = 2²","8 = 2⁴"],1],["Какой двоичной триаде соответствует восьмеричная цифра 7?",["111","011","110","101"],0],["Как переводится двоичное число в восьмеричное?",["Умножением на 2³","Группировкой слева направо по две","Группировкой справа налево по три","Делением на 8"],2],["Сколько двоичных цифр заменяет одна восьмеричная цифра?",["две","четыре","три","одну"],2],["В каком порядке читаются остатки при переводе десятичного числа в восьмеричное?",["В прямом порядке","Слева направо","В обратном порядке","В порядке деления"],2],["Восьмеричная система связана с двоичной тем, что 8=2³.",["Верно","Неверно"],0],["При переводе двоичного числа в восьмеричное запись группируют справа налево по три цифры.",["Верно","Неверно"],0],["Переведите 356₈ в десятичную систему счисления.",null,"238"],["Запишите результат перевода 202₁₀ в восьмеричную систему.",null,"312"]]},
  {title:"Вариант 4",questions:[
    ["Почему запись 128₈ невозможна?",["Цифра 1 не входит в алфавит","Число слишком большое","Цифра 8 не входит в восьмеричный алфавит","Основание должно быть 10"],2],["Какие цифры входят в алфавит восьмеричной системы счисления?",["От 0 до 7","От 1 до 8","От 0 до 8","От 0 до 9"],0],["Сколько двоичных цифр составляет одна триада?",["8","3","4","2"],1],["По сколько цифр группируют двоичную запись при переводе в восьмеричную систему?",["По две","По три","По восемь","По четыре"],1],["Какая из записей невозможна в восьмеричной системе счисления?",["356₈","572₈","128₈","641₈"],2],["Чему равно 572₈ в двоичной системе?",["111010101","11010111","001010111","101111010"],1],["Каждой восьмеричной цифре соответствует четыре двоичные цифры.",["Верно","Неверно"],1],["При переводе десятичного числа в восьмеричное остатки читают в прямом порядке.",["Верно","Неверно"],1],["Переведите 119₁₀ в восьмеричную систему счисления.",null,"167"],["Запишите результат перевода 202₁₀ в восьмеричную систему.",null,"312"]]}
];

const commonQuestions = [
  ["Исправьте утверждение: восьмеричная система использует цифры от 0 до 9.",["От 0 до 7","От 1 до 8","От 0 до 8","От 0 до 9"],0],
  ["Для перехода из десятичной системы в восьмеричную число делят на...",["2","8","10","3"],1],
  ["Каждой цифре восьмеричной системы соответствует группа из... двоичных знаков.",["2","4","3","8"],2],
  ["Запись 58₈ корректна.",["Верно","Неверно"],1],
  ["При переходе из десятичной системы остатки от деления на 8 читают...",["в прямом порядке","в обратном порядке","слева направо без изменений","по два"],1],
  ["Почему между восьмеричной и двоичной системами не нужно выполнять деление?",null,"Потому что 8 = 2³ и каждой восьмеричной цифре соответствует триада"],
  ["Что заменяет одну цифру восьмеричной системы при переходе через двоичную?",["Триада из трёх двоичных знаков","Четыре двоичных знака","Две двоичные знака","Одна десятичная цифра"],0],
  ["Переведите число 73₁₀ в восьмеричную систему.",null,"111"],
  ["Переведите число 58₁₀ в восьмеричную систему.",null,"72"]
];

let selectedVariant = Math.floor(Math.random() * variants.length);
const $ = selector => document.querySelector(selector);
const questions = () => [...variants[selectedVariant].questions, ...commonQuestions];

function drawCardCanvas(canvas){const ctx=canvas.getContext('2d');canvas.width=canvas.clientWidth*devicePixelRatio;canvas.height=canvas.clientHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);ctx.strokeStyle='rgba(101,255,155,.18)';for(let x=20;x<canvas.clientWidth;x+=42){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.clientHeight);ctx.stroke()}for(let y=18;y<canvas.clientHeight;y+=30){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.clientWidth,y);ctx.stroke()}}
function renderQuiz(){const qs=questions();$('#quiz').innerHTML=qs.map((q,i)=>{const open=!q[1],numeric=i>=17;const options=open?'':`<div class="options">${q[1].map((o,j)=>`<div class="option"><input type="radio" name="q${i}" id="q${i}-${j}" value="${j}"><label for="q${i}-${j}">${String.fromCharCode(1040+j)}) ${o}</label></div>`).join('')}</div>`;return `<article class="question panel" id="question-${i}"><canvas class="question-canvas" aria-hidden="true"></canvas><div class="question-content"><div class="question-head"><span class="question-number">${String(i+1).padStart(2,'0')}</span><h3 class="question-title">${q[0]}</h3><span class="question-type">${open?'ОТКРЫТЫЙ ОТВЕТ':q[1].length===2?'ВЕРНО / НЕВЕРНО':'ОДИН ОТВЕТ'}</span></div>${open?`<div class="answer-input"><input type="${numeric?'number':'text'}" ${numeric?'inputmode="numeric" step="1" min="0"':''} name="q${i}" aria-label="Ответ на задание ${i+1}" placeholder="${numeric?'Введите число':'Введите ответ'}"></div>`:options}</div></article>`}).join('');document.querySelectorAll('.question-canvas').forEach(drawCardCanvas);document.querySelectorAll('#quiz input').forEach(x=>x.addEventListener('input',updateProgress));updateProgress()}
function getAnswers(){return Array.from({length:QUESTION_COUNT},(_,i)=>{const radio=document.querySelector(`[name=q${i}]:checked`),text=document.querySelector(`[name=q${i}][type=text], [name=q${i}][type=number]`);return radio?radio.value:(text?.value.trim()||'')})}
function updateProgress(){const a=getAnswers(),n=a.filter(Boolean).length,p=Math.round(n/QUESTION_COUNT*100);$('#progressText').textContent=`${n} из ${QUESTION_COUNT} отвечено`,$('#progressPercent').textContent=`${p}%`,$('#progressBar').style.width=`${p}%`}
function normalize(v){return String(v).toLowerCase().replace(/[₈₁₀₂]/g,'').replace(/\s+/g,'').replace(/[^0-9a-zа-я]/gi,'')}
function scoreQuiz(){const qs=questions(),answers=getAnswers();return qs.map((q,i)=>{const answer=answers[i],open=!q[1],correct=open?q[2]:String(q[2]),answerText=open?answer:(answer!==''&&q[1][Number(answer)]!==undefined?q[1][Number(answer)]:'');const correctText=open?String(q[2]):q[1][Number(q[2])];return {number:i+1,answer,answerText,correct,correctText,open,isCorrect:!!answer&&normalize(answer)===normalize(correct),question:q[0]}})}
function formatResults(rows){return rows.map(r=>{const status=r.isCorrect?'ВЕРНО':r.answerText?'ОШИБКА':'НЕТ ОТВЕТА';return [`Задание ${r.number}: ${r.question}`,`Ответ ученика: ${r.answerText||'нет ответа'}`,`Правильный ответ: ${r.correctText}`,`Результат: ${status}`].join('\n')}).join('\n\n')}
async function checkOpenAnswer(row){if(!row.answer)return false;try{const response=await fetch(`${AI_BASE_URL}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${AI_API_KEY}`},body:JSON.stringify({model:AI_MODEL,temperature:0,messages:[{role:'system',content:'Проверь учебный ответ. Верни только JSON без markdown в формате {"correct":true} или {"correct":false}. Считай ответ правильным, если смысл совпадает с эталоном, даже при другой формулировке.'},{role:'user',content:`Вопрос: ${row.question}\nЭталон: ${row.correct}\nОтвет ученика: ${row.answer}`}]})});if(!response.ok)throw new Error(`AI HTTP ${response.status}`);const data=await response.json();const text=data.choices?.[0]?.message?.content||'';const parsed=JSON.parse(text.match(/\{[\s\S]*\}/)?.[0]||'{}');return parsed.correct===true}catch(error){console.warn('AI check failed, local answer check kept',error);return row.isCorrect}}
async function sendToSheets(payload,timeoutMs=10000){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),timeoutMs);try{await fetch(SHEETS_ENDPOINT,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload),signal:controller.signal,keepalive:true});return true}catch(error){console.warn('Google Sheets request failed',error);return false}finally{clearTimeout(timeout)}}
function checkStudentName(name){return new Promise(resolve=>{const callback='sheetCheck_'+Date.now()+'_'+Math.floor(Math.random()*1000),script=document.createElement('script'),timeout=setTimeout(()=>{cleanup();resolve(true)},5000);function cleanup(){clearTimeout(timeout);delete window[callback];script.remove()}window[callback]=data=>{cleanup();resolve(!data.exists)};script.src=`${SHEETS_ENDPOINT}?action=check&studentName=${encodeURIComponent(name)}&callback=${callback}`;script.onerror=()=>{cleanup();resolve(true)};document.body.appendChild(script)})}
async function saveResult(results){const completedAt=new Date().toISOString();const payload={action:'save',studentName:$('#studentName').value.trim(),variant:selectedVariant+1,completedAt,score:results.filter(x=>x.isCorrect).length,total:QUESTION_COUNT,answers:results,results:formatResults(results)};payload.saved=Boolean(SHEETS_ENDPOINT)&&await sendToSheets(payload);return payload}
function showLoading(){const screen=$('#loadingScreen');screen.hidden=false;window.scrollTo({top:0,behavior:'smooth'});const canvas=$('#loadingCanvas'),ctx=canvas.getContext('2d');let angle=0,frame;function draw(){ctx.clearRect(0,0,180,180);ctx.save();ctx.translate(90,90);ctx.rotate(angle);for(let i=0;i<8;i++){ctx.rotate(Math.PI/4);ctx.fillStyle=`rgba(101,255,155,${(i+2)/10})`;ctx.fillRect(42,-2,18,4)}ctx.restore();angle+=.06;frame=requestAnimationFrame(draw)}draw();return()=>{cancelAnimationFrame(frame);screen.hidden=true}}
async function requestAiReview(payload){if(!SHEETS_ENDPOINT||!payload.answers.some(row=>row.open&&row.answer))return false;return sendToSheets({...payload,action:'ai-review'},60000)}
async function finish(){const name=$('#studentName').value.trim();if(!name){$('#studentName').focus();$('#studentName').setCustomValidity('Введите имя и фамилию');$('#studentName').reportValidity();return}if(!(await checkStudentName(name))){alert('Работа с таким именем и фамилией уже сохранена. Повторная отправка запрещена.');return}$('#studentName').setCustomValidity('');const results=scoreQuiz(),loadingStarted=performance.now();const hideLoading=showLoading();const payload=await saveResult(results);await requestAiReview(payload);await new Promise(resolve=>setTimeout(resolve,Math.max(0,700-(performance.now()-loadingStarted))));hideLoading();renderResults(results,payload.saved)}
function renderResults(rows,saved){$('#quizForm').hidden=true;const correct=rows.filter(x=>x.isCorrect).length;$('#results').hidden=false;$('#results').innerHTML=`<div class="section-kicker">СЕАНС ЗАВЕРШЁН // ВАРИАНТ ${selectedVariant+1}</div><h2>Результат для ${$('#studentName').value.trim()}</h2><div class="score">${correct} / ${QUESTION_COUNT}</div><p class="field-hint">${saved?'Результат отправлен в таблицу. Открытые ответы дополнительно проверяются нейросетью.':'Не удалось отправить результат в таблицу. Проверьте публикацию Apps Script и доступ «Все».'}</p><div class="result-list">${rows.map(r=>`<div class="result-row ${r.answer?(r.isCorrect?'correct':'wrong'):'unanswered'}"><span class="result-icon">${r.answer?(r.isCorrect?'OK':'×'):'—'}</span><span><strong>${String(r.number).padStart(2,'0')}</strong> ${r.question}</span><span class="result-answer">${r.answer?`Ваш ответ: ${r.answer}`:'Нет ответа'}${r.isCorrect?'':`<br>Ключ: ${r.correct}`}</span></div>`).join('')}</div>`;window.scrollTo({top:0,behavior:'smooth'})}

$('#finishButton').addEventListener('click',()=>{const firstMissing=getAnswers().findIndex(answer=>!answer);if(firstMissing>=0){$('#confirmText').textContent=`Не заполнено заданий: ${getAnswers().filter(answer=>!answer).length}. После подтверждения работа будет сохранена.`;$('#confirmModal').hidden=false;$('#cancelFinish').onclick=()=>{$('#confirmModal').hidden=true;document.querySelector(`#question-${firstMissing}`).scrollIntoView({behavior:'smooth',block:'center'})};}else finish()});$('#confirmFinish').addEventListener('click',()=>{$('#confirmModal').hidden=true;finish()});
const matrix=$('#matrix'),mctx=matrix.getContext('2d');let drops=[],lastMatrixFrame=0;const matrixStep=29,matrixSpeed=.07,matrixTrail=6,matrixDpr=Math.min(devicePixelRatio||1,1.5);function resizeMatrix(){matrix.width=Math.round(innerWidth*matrixDpr);matrix.height=Math.round(innerHeight*matrixDpr);mctx.setTransform(matrixDpr,0,0,matrixDpr,0,0);drops=Array.from({length:Math.ceil(innerWidth/matrixStep)},()=>Math.random()*(innerHeight/22))}function matrixFrame(time){if(time-lastMatrixFrame<42){requestAnimationFrame(matrixFrame);return}const delta=Math.min(60,time-lastMatrixFrame||42);lastMatrixFrame=time;mctx.fillStyle='rgba(0,0,0,.48)';mctx.fillRect(0,0,innerWidth,innerHeight);mctx.font='bold 20px monospace';mctx.textAlign='center';mctx.shadowBlur=0;drops.forEach((y,i)=>{const x=i*matrixStep+matrixStep/2,head=y*22;for(let trail=matrixTrail;trail>=0;trail--){const yy=head-trail*22;if(yy<0||yy>innerHeight)continue;const alpha=trail===0?1:Math.max(.12,1-trail*.15);mctx.fillStyle=trail===0?'#eafff0':`rgba(48,255,112,${alpha})`;if(trail===0){mctx.shadowColor='#39ff88';mctx.shadowBlur=10}mctx.fillText(String((i+Math.floor(y)+trail)%8),x,yy)}mctx.shadowBlur=0;if(head>innerHeight+170)drops[i]=Math.random()*-12;drops[i]+=matrixSpeed*delta/16.67});requestAnimationFrame(matrixFrame)}addEventListener('resize',resizeMatrix);resizeMatrix();requestAnimationFrame(matrixFrame);renderQuiz();
